# Generated by Django 4.0.5 on 2022-07-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='specialist',
            name='unique',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='schedule',
        ),
        migrations.AddField(
            model_name='specialist',
            name='schedule',
            field=models.ManyToManyField(to='service_app.schedule'),
        ),
    ]
