# Generated by Django 4.0.5 on 2022-07-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_remove_specialist_unique_remove_specialist_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='location',
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='service_app.location'),
            preserve_default=False,
        ),
    ]
