# Generated by Django 4.0.5 on 2022-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_remove_specialist_location_schedule_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='location',
        ),
        migrations.AddField(
            model_name='specialist',
            name='location',
            field=models.ManyToManyField(to='service_app.location'),
        ),
    ]
